### ISSUE TITLE
[FR] Pass initial map center through config

### ISSUE THREAD

**Issue by jsblair9** [AndrewHaine/statamic-cartographer#2]
Would be nice to be able to set the map fieldtype's initial centering location through the settings instead of hardcoding the value in the initial `blank() `

**Comment by AndrewHaine** [comment]
Merged in #4 :) Field config now has an array field for default center lat/lng 
<img width="880" alt="Screenshot 2019-06-24 at 18 56 34" src="https://user-images.githubusercontent.com/16389134/60040904-f24cad80-96b1-11e9-9a15-8d988b89ef0a.png">

**Comment by jsblair9** [comment]
awesome! I think that will be a great feature addition

**Comment by AndrewHaine** [comment]
Released in v1.0.1 :)
